# Generated by Django 3.2 on 2025-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=6, unique=True, verbose_name='Цвет тега'),
        ),
    ]
