# Generated by Django 3.2 on 2025-03-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptions_subscription_prevent_self_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='subscription_prevent_self_subscription',
        ),
    ]
