# Generated by Django 3.2 on 2025-03-08 12:44

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subscriptions_subscription_prevent_self_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='subscription_prevent_self_subscription'),
        ),
    ]
